### PR TITLE
Update posts for Depth Estimation 

### PR DESCRIPTION
**Pull request by vaibhawkhemka**

### CODE REVIEW

**Review by luiky — APPROVED** [review]

**Comment by luiky** [comment]
Hi Vaibhaw ,
Could you edit index.md file to included a link to your post02.md? As it has been done for the first post.
Please, check the file to understand me completely.
https://github.com/vaibhawkhemka/web/blob/master/gsoc/2021/posts/index.md

Thank you.

**Comment by vaibhawkhemka** [comment]
Hi @luiky,
I have done the changes as you mentioned.
Thanks

**Comment by luiky** [comment]
Ok, but I can't see the pull request ?¿?
thanks

**Comment by luiky** [comment]
Hi again, @vaibhawkhemka 
I think that the commit & PR over the index.md is not done. Check it, please!
Thanks again.

**Comment by vaibhawkhemka** [comment]
Hi, @luiky 
Sorry for the delay. I have created a PR for post 03 and updated the index.md file.

**Pull request merged**
