### PR TITLE
added post2

### PR DESCRIPTION
**Pull request by piyushpilaniya**

### CODE REVIEW

**Comment by Fahani** [comment]
Thanks @piyushpilaniya

**Comment by Fahani** [comment]
Don't forget to include the link in the Index page. Also be careful, you use capital letter P in the word "Post2". Change it to lower case plase

**Comment by piyushpilaniya** [comment]
Ok sir I will take from now onwards...Thank You

**Comment by Fahani** [comment]
You are welcome, whenever you can, update changes and make a pull request. Thank you

**Pull request merged**
