### PR TITLE
Added 7th post

### PR DESCRIPTION
**Pull request by ksakash**
This post describes Slice, specific language for ICE, and how it is used in `robocomp` and `gazebo-robocomp` integration.

### CODE REVIEW

**Comment by Fahani** [comment]
Good job @ksakash !

**Comment by Fahani** [comment]
I think the link to the picture in your post number 9 has to be edited

**Comment by ksakash** [comment]
But it is looking good in markdown. What could be the problem in rendering?

**Comment by Fahani** [comment]
Try this url: https://raw.githubusercontent.com/ksakash/README/master/gsoc.png

**Pull request merged**
